apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - external-secret.yaml
  - service-account.yaml
  - deployment.yaml
  - service.yaml
  - pod-disruption-budget.yaml
  - network-policy.yaml

configMapGenerator:
  - name: demo-service-config
    literals:
      - SERVICE_NAME=demo-service
      - DEMO_FAILURE_MODE=none
      - FAILURE_DELAY_MS=2500

generatorOptions:
  labels:
    app.kubernetes.io/name: demo-service
    app.kubernetes.io/part-of: customer-experience-platform
    backstage.io/kubernetes-id: demo-service

labels:
  - pairs:
      app.kubernetes.io/name: demo-service
      app.kubernetes.io/part-of: customer-experience-platform
      app.kubernetes.io/managed-by: argocd
      backstage.io/kubernetes-id: demo-service
