apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo-service-development
resources:
  - ../../base

images:
  - name: ghcr.io/stonetusker/tusker-demo-notification-service
    newName: ghcr.io/stonetusker/tusker-demo-notification-service
    newTag: c8c2f2214d85baa3ce894695d0863113caf2a429

replicas:
  - name: demo-service
    count: 2

configMapGenerator:
  - name: demo-service-config
    behavior: merge
    literals:
      - DEMO_FAILURE_MODE=none
      - FAILURE_DELAY_MS=2500

labels:
  - pairs:
      app.kubernetes.io/environment: development

commonAnnotations:
  tuskerblueprint.io/release-sha: c8c2f2214d85baa3ce894695d0863113caf2a429

patches:
  - path: deployment-selector-compatibility.yaml
