apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo-service-development
resources:
  - ../../base

images:
  - name: ghcr.io/stonetusker/tusker-demo-notification-service
    newName: ghcr.io/stonetusker/tusker-demo-notification-service
    newTag: 1db6fae5f0b9d400583a5480ef397d28de1f77d5

replicas:
  - name: demo-service
    count: 2

configMapGenerator:
  - name: demo-service-config
    behavior: merge
    literals:
      - DEMO_FAILURE_MODE=none
      - FAILURE_DELAY_MS=2500

labels:
  - pairs:
      app.kubernetes.io/environment: development

commonAnnotations:
  tuskerblueprint.io/release-sha: 1db6fae5f0b9d400583a5480ef397d28de1f77d5

patches:
  - path: deployment-selector-compatibility.yaml
