apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo-service-development
resources:
  - ../../base

images:
  - name: ghcr.io/stonetusker/tusker-demo-notification-service
    newName: ghcr.io/stonetusker/tusker-demo-notification-service
    newTag: c8c2f222c42a0c5e63c8e763df44a6edc3ebc2d0

replicas:
  - name: demo-service
    count: 2

configMapGenerator:
  - name: demo-service-config
    behavior: merge
    literals:
      - DEMO_FAILURE_MODE=none
      - FAILURE_DELAY_MS=2500

labels:
  - pairs:
      app.kubernetes.io/environment: development

commonAnnotations:
  tuskerblueprint.io/release-sha: c8c2f222c42a0c5e63c8e763df44a6edc3ebc2d0

patches:
  - path: deployment-selector-compatibility.yaml
